### ISSUE TITLE
Docker Hub out of sync

### ISSUE THREAD

**Issue by frostieDE** [blacklabelops/confluence#52]
It seems as Docker Hub is not aware of the new version which is stated here on GitHub, see https://hub.docker.com/r/blacklabelops/confluence/tags/ and https://hub.docker.com/r/blacklabelops/confluence/ :wink:

**Comment by blacklabelops** [comment]
Fixed.

**Comment by frostieDE** [comment]
LGTM (but in fact this page still shows an old README.md https://hub.docker.com/r/blacklabelops/confluence/)

**Comment by blacklabelops** [comment]
I am using Jenkins and CircleCI for build jobs. There is no way to update readme on DockerHub automatically.

**Comment by frostieDE** [comment]
Again, Docker Hub is not aware of the latest version of Confluence :-(

**Comment by blacklabelops** [comment]
Build system is down, trying to recover.
